/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package {
	import flash.display.Sprite;
	
	import gamescene.prefabs.explosions.ExplosionPrefab;
	
	public class FlexUnitCompilerApplication extends Sprite {
		
		private var gamescene_prefabs_explosions_ExplosionPrefab_obj:gamescene.prefabs.explosions.ExplosionPrefab;
	}
}